In [1]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[6,7,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[10 20 30 40 50]
[6 7 9 7 1]
[16 27 39 47 51]
[ 4 13 21 33 49]
[ 60 140 270 280  50]
[ 1.66666667  2.85714286  3.33333333  5.71428571 50.        ]


In [2]:
print(a.dot(b))
sclr=3
print("Scalar Value:",sclr)
print("Array:",a)
print("Result:",a*sclr)

800
Scalar Value: 3
Array: [10 20 30 40 50]
Result: [ 30  60  90 120 150]


In [3]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,4],[5,9]])
print(a%b)

[[1 0]
 [0 4]]


In [10]:
def my_function(x,y):
    if x>y:
        return x-y
    else:
        return x+y
    arr1=[10,20,30,40]
    arr2=[2,10,35,25]
    vect_func=np.vectorize(my_func)
    print("Array1:",arr1)
    print("Array2:",arr2)
    print("Result:",vect_func(arr1,arr2))


In [14]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[10,20,30,40]
arr2=[2,10,35,25]
vect_func=np.vectorize(my_func)
print("Array1:",arr1)
print("Array2:",arr2)
print("Result:",vect_func(arr1,arr2))

Array1: [10, 20, 30, 40]
Array2: [2, 10, 35, 25]
Result: [ 8 10 65 15]
