In [3]:
import numpy as np
array=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarray=array.reshape(4,3)
print (array)
print(newarray)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [4]:
import numpy as np
flat=array.flatten()
print(array)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [6]:
print("array dimension:",array.ndim)
print("shape of array:",array.shape)
print("type of element:",array.dtype)
print("Total no of elements:",array.size)

array dimension: 2
shape of array: (3, 4)
type of element: int64
Total no of elements: 12


In [7]:
newtype=array.astype('f')
print("\n Convert array:\n",newtype)
print("\n Convert array type:\n",newtype.dtype)


 Convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 Convert array type:
 float32


In [8]:
size=len(array)
print("\n size of the array:\n",size)


 size of the array:
 3
